### ISSUE TITLE
Support DateTime picker as Input type.

### ISSUE THREAD

**Issue by polyakov-v** [tghamm/dynamic-linq-query-builder#110]
Currently, when I try to write something like
```cs
var dates = definitions.First(p => p.Field == "StartTimeUtc");
dates.Input = "date";
```

It seems that it is not supported. 
I am getting a JavaScript error:
```
jquery.min.js:2 Uncaught ConfigError: Invalid input "date"
    at k.error (query-builder.standalone.min.js:8:6349)
    at f.<anonymous> (query-builder.standalone.min.js:7:12317)
    at Array.forEach (<anonymous>)
    at f.checkFilters (query-builder.standalone.min.js:7:11995)
    at f.init (query-builder.standalone.min.js:7:11663)
    at new f (query-builder.standalone.min.js:7:5447)
    at $.fn.queryBuilder (query-builder.standalone.min.js:8:7453)
    at HTMLDocument.<anonymous> ((index):98:56)
    at e (jquery.min.js:2:30005)
    at t (jquery.min.js:2:30307)
```

**Comment by tghamm** [comment]
Hi, you'd want to implement it as follows: with the caveat that this is checked into the master branch but won't be released until next week - check and run the Example project for a working example of how it will work:
https://github.com/tghamm/dynamic-linq-query-builder/blob/d5cca23a6e7829b0b9b85d69fd368557576808fa/Castle.DynamicLinqQueryBuilder.Example/Controllers/HomeController.cs#L36-L44
